permalink: /:categories/:title/
exclude:
  - README.md
  - Capfile
  - config

url: https://rad-pooch.cloudvent.net
name: rerad-pooch.cloudvent.net
disqus_shortname: restcookbook

google_analytics: UA-53222355-1
